# Generated by Django 6.0.4 on 2026-05-23 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthfacility',
            options={},
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='facility_name',
        ),
        migrations.AddField(
            model_name='diseaserecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='cases',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='deaths',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='disease_name',
            field=models.CharField(choices=[('Malaria', 'Malaria'), ('Cholera', 'Cholera'), ('Lassa Fever', 'Lassa Fever'), ('COVID-19', 'COVID-19'), ('Measles', 'Measles'), ('Typhoid', 'Typhoid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
